---
name: VanillaMinecarts
version: 1.0.0
main: pixelwhiz\vanillaminecarts\VanillaMinecarts
api: 5.0.0
author: pixelwhiz
website: https://github.com/pixelwhiz/VanillaMinecarts
src-namespace-prefix: pixelwhiz\vanillaminecarts

...
